"""test running migrations

Revision ID: 3fa3ee4f3f28
Revises: 3e4e2d757e80
Create Date: 2023-11-09 01:10:04.053844

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3fa3ee4f3f28"
down_revision: Union[str, None] = "3e4e2d757e80"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
