"""test running migrations

Revision ID: 3fe5f3b1cd1d
Revises: 7e001ac1343e
Create Date: 2023-11-09 02:35:42.758581

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3fe5f3b1cd1d"
down_revision: Union[str, None] = "7e001ac1343e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
