"""test running migrations

Revision ID: 634f89f734b9
Revises: 8dc69b7fcd9a
Create Date: 2023-11-13 00:52:25.388824

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "634f89f734b9"
down_revision: Union[str, None] = "8dc69b7fcd9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
