"""test running migrations

Revision ID: 71d0f0545d03
Revises: 3e223ac8ce74
Create Date: 2023-11-13 03:07:24.713022

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "71d0f0545d03"
down_revision: Union[str, None] = "3e223ac8ce74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
