"""test running migrations

Revision ID: b22bfb3e3ee9
Revises: 7f0f3ca03e38
Create Date: 2023-11-13 00:41:10.745717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b22bfb3e3ee9'
down_revision: Union[str, None] = '7f0f3ca03e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
